### ISSUE TITLE
Folders to appear above files

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#1]
Hi, I'm confused when seeing files above folders. Could we have it reversed so that it follows default rendering of tree view?

Thank you

**Comment by Thomas-McKanna** [comment]
Thank you for your interest in the project! I like the idea - I'll implement it this weekend.

**Comment by Thomas-McKanna** [comment]
@robertpiosik I've push an updated version of the extension (v1.2.0). If it looks good, feel free to close this issue. And let me know if you have more ideas.
