### ISSUE TITLE
Add the recomended system message by default

### ISSUE THREAD

**Issue by Antoine-lb** [Thomas-McKanna/Files2Prompt#12]
"Always provide full code listings. You only need to include files that have changed. I repeat, ALWAYS provide full code listings. Your output should be in XML format (in a code block) that mirrors the input format (that is, `<files>` element with a list of `<file>` in the interior)."

Hello again 👋
The current message is compatible with any programing language and coding style, so I don't see why someone would change it.

So why not simply add it by default?

**Comment by Thomas-McKanna** [comment]
The reason I did not set it as the default is that is will cause all output to be XML and only contain the output files with no additional explanation. I didn't necessarily want to make my personal workflow the default workflow for everyone. I envisioned the most users might just want to use the plugin for its ability to quickly select files and turn them into a prompt, and the pure XML output from the LLM might be unexpected in this case and drive them away from the plugin unless they actually take time to read the readme.

I'm definitely open to changing this default behavior, but I'm not convinced yet it is the best move.

I'd like to keep this pull request open. For people reading this, if you agree that the recommended system message should be the default, please reply to @Antoine-lb's post with 👍. If it seems to be a popular opinion, I'll change it.

**Comment by Antoine-lb** [comment]
You are absolutely right. 

I'm asking for the things I don't like the AI IDEs for, this "black box" context that I don't understand.

I'm here bc I think this apps should let the developer build the context as they see fit, and not impose how to do it.

My analogy is that I want a racing car with manual controls, not a automatic SUV. 

Good call, I will close it
