### ISSUE TITLE
Add a Play button to apply the changes

### ISSUE THREAD

**Issue by Antoine-lb** [Thomas-McKanna/Files2Prompt#14]
<img width="172" alt="SCR-20241216-svwx" src="https://github.com/user-attachments/assets/08e71051-e58d-4158-8559-088441db6c90" />

Sorry for spamming 🙏

Having to click on the browserfile and then pasting is not intuitive. A "Apply" button that simply read the clipboard could make it nicer.

Thanks!
- Antoine

**Comment by Thomas-McKanna** [comment]
I'll work on getting this one added. It is pretty straightforward.

**Comment by Thomas-McKanna** [comment]
This one should be implemented by the latest version of the extension (v1.7.3). Let me know if it looks good and works as expected.

**Comment by Antoine-lb** [comment]
Works perfectly, thanks!
