### ISSUE TITLE
Create presets of selected elements

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#3]
When working with monorepo I often find myself switching between sets of selected folders. It would be nice to have these quickly selected based on previous saved selections.

**Comment by Thomas-McKanna** [comment]
This is an interesting feature. I also have had cases were I am switching between different sets of folders and basically have to clear my selection each time.

I'm trying to envision what this feature would look like. Perhaps you can help me brainstorm. Maybe I could add some save button to save the current selection of files. Clicking save would cause VS code to request a name for the collection. Then you could select from your collections with a dropdown at the top of the extension UI.

The challenge with this is storing the data persistently. I'm fairly new to VS Code extensions so I'm not sure how feasible this is.

**Comment by Thomas-McKanna** [comment]
I like that approach. Usage of the copy button/function could trigger snapshots in file selection that can be navigated with `↶` and `↷`. Let me ponder on this one a bit more.

**Comment by Thomas-McKanna** [comment]
@robertpiosik I have just pushed v1.3.0 which adds the arrow buttons. Let me know what you think.
