### ISSUE TITLE
Images should not be copied

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#7]
Images should not be copied.

**Comment by Thomas-McKanna** [comment]
Great idea. I think this issue will continue to pop up with other file types, and a user may even want to customize this.

So, my plan is to add a new extension setting where you can provide a comma-separated list of file extensions which by default should not be selected (they can still be manually selected, just like with gitignored filed). I will default this list to contain common image extensions like png, jpg, jpeg, and webp.

What do you think of this approach? Any other file extensions you can think of which would probably be safe to ignore?

Planning on getting to this during the weekend.

**Comment by Thomas-McKanna** [comment]
This should be implemented with the latest version.
