### ISSUE TITLE
Support for symlinked directories

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#8]
Thank you for all your work on this extension. I use it all the time and it's a lifesaver to me.

My use case involves using shared library that is symlinked, my current workaround is to have it opened in other window but it makes it impossible to copy other files I work on in one pass.

Cheers!

**Comment by Thomas-McKanna** [comment]
Thank you for all of your suggestions. Without your suggested features, that extension would not be nearly as good as it is now.

Can you give me a more detailed example of what you mean? I haven't run into this issue. Do symlinked files not show up in the file tree?

I will get to this one by the weekend at the latest.

**Comment by Thomas-McKanna** [comment]
This one is implemented with v1.7.0.
