### ISSUE TITLE
Restore tree state on back/forward navigation

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#9]
It would be cool if the tree restore its state while doing back/forward history. This way we could clearly see what is selected when the tree is collapsed.

**Comment by Thomas-McKanna** [comment]
Can you explain a little more what this would look like? When you say the state do you mean which folders are expanded/collapsed?

**Comment by Thomas-McKanna** [comment]
I tried for a while to figure out how to do this one, but I'm struggling to get the directory expanded/collapsed state to actually update in the UI. Not sure why it's not updating.
